export const archetypeDescriptions: Record<string, string> = {
  hero: `When faced with challenge, you instinctively rise to meet it. For you, action is language and purpose is belief. You carry the weight of responsibility with clarity, finding certainty in your ability to solve problems. Yet the same force that drives you forward can isolate you when strength becomes proof of worth. The mature Hero learns that true courage is not fearlessness, but endurance — acting with grace even when the path is unclear. Through your pursuit of order, you also discover meaning.`,

  sage: `You are driven by a hunger to understand — not just how things work, but why they exist. You observe patterns, analyze structure, and turn confusion into clarity. Knowledge gives you freedom, and logic gives you calm. Yet when reflection becomes excess, thought can harden into distance. The true Sage learns when to stop seeking and begin perceiving — when wisdom is not accumulation but awakening. In that pause, understanding becomes compassion.`,

  lover: `You live through feeling, drawn to connection and intimacy. You sense the emotional temperature of relationships and bring warmth where others bring distance. You seek to be understood, and to understand through closeness. Yet love’s challenge lies in overextension — losing yourself in the pursuit of harmony. The mature Lover discovers that tenderness is not weakness but rhythm: the dance between merging and autonomy, between devotion and selfhood.`,

  ruler: `You have a natural instinct for structure. You bring order to chaos, shaping systems that allow others to flourish. Responsibility comes naturally to you; you prefer design over disorder, decision over drift. Yet the burden of control can become a cage. True rulership requires trust — the art of governing by clarity, not command. When you learn to build frameworks that liberate rather than confine, your authority transforms into harmony.`,

  explorer: `You are a wanderer of both the world and the self. Freedom is your compass; curiosity, your engine. You venture into the unknown not to escape, but to discover what remains real within you. Still, constant motion can dissolve direction. The mature Explorer learns that freedom is not absence of boundaries, but the choice to cross them consciously. Wherever you go, you are both traveler and home.`,

  creator: `You are compelled to give form to feeling — to translate imagination into shape. You build, paint, write, design, or compose not for display, but for coherence. Creation is your dialogue with existence. Yet perfectionism can turn inspiration into paralysis. The true Creator learns to let process lead product, to trust that beauty arises not from control but from flow. What you make is not merely art — it’s the language of becoming.`,

  visionary: `You see patterns others miss. The future speaks to you in fragments, and you translate its whispers into possibilities. You connect the abstract and the immediate, shaping narratives that guide direction. Yet the gift of vision demands grounding; otherwise, imagination becomes drift. The mature Visionary learns to root the unseen in the present, to weave light into reality. Your foresight becomes not prophecy, but guidance.`,

  magician: `You perceive transformation where others see chaos. You understand that every change outside mirrors a change within. Through intuition and intention, you shift perception, turning endings into beginnings. But magic without humility becomes illusion. The true Magician channels energy, not controls it — listening to the rhythm of emergence instead of forcing the outcome. You don’t alter reality; you reveal its hidden symmetry.`,

  trickster: `You play with the world’s rules to show their limits. Humor is your instrument, paradox your language. You delight in disrupting rigidity, turning seriousness into movement. Yet rebellion for its own sake can become avoidance. The mature Trickster transforms mischief into wisdom — teaching others to laugh at illusion, to unfreeze what has grown heavy. Your chaos is not destruction, but renewal disguised as play.`,

  caregiver: `You sense the unspoken needs of others and move instinctively to ease their pain. Your warmth restores trust, your patience repairs what is broken. You give because empathy is your nature. Yet giving without boundaries can erode the self. The true Caregiver learns that nurturing requires balance — that tending to one’s own roots allows others to grow. Compassion becomes a circulation, not depletion.`,

  everyman: `You find meaning in the ordinary and beauty in the familiar. You believe belonging is not earned but lived. People feel safe with you because you carry no pretense — you meet them as they are. Yet the desire to fit in can blur your edges. The mature Everyman learns that authenticity, not conformity, creates connection. By embracing your own simplicity, you become the mirror through which others recognize themselves.`,

  mother: `You embody nourishment — the instinct to hold, to heal, to sustain. You bring stability through care, creating space where life can grow. Yet endless responsibility can harden into fatigue. True motherhood, symbolic or literal, is not sacrifice but flow: knowing when to cradle and when to release. You create by allowing — by trusting that love, when ungrasped, continues to grow in freedom.`,

  rebirth: `You are familiar with endings and the silent moments that follow. You’ve watched structures collapse and learned to gather their fragments anew. Each cycle strips away illusion and returns you closer to essence. But constant reinvention can become exile if you forget to arrive. The mature Rebirth learns that transformation is not about change, but return — becoming who you always were, beneath the ruins.`,

  innocent: `You hold a rare clarity of heart. Even in disappointment, you search for goodness and refuse to abandon faith in life. Your hope is not naive — it is regenerative. Yet to deny pain is to deny truth. The mature Innocent learns to trust again, not blindly but bravely, seeing complexity without losing purity. You remind the world that sincerity is still a form of strength.`,

  philosopher: `You live within thought, drawing connections between the abstract and the intimate. You analyze, synthesize, and translate confusion into frameworks. Yet reason without warmth can freeze understanding. The true Philosopher learns that insight deepens through feeling — that intellect matures only when it allows intuition to speak. You are not just a thinker, but a weaver of meaning.`,
};
